export const Strings = {
  noInternet: 'No Internet Connection',
  noInternetDescription: 'You are currently offline. The app will show previously saved characters.',
  loading: 'Loading...',
  okButton: 'OK',
  saved: 'Saved!',
  error: 'Error',
  failed: 'Failed to save offline.',
  savedDescription: 'This character is now available offline.',
  about: "Welcome to the Rick and Morty Explorer – a fun and interactive mobile app for fans of the hit animated series Rick and Morty! This app lets you dive into the universe of the show by browsing through an extensive list of characters, exploring their profiles, and learning fun facts about them. Whether you're a casual viewer or a hardcore fan, this app brings the multiverse to your fingertips.",
  keyFeatures: 'Key Features',
  liveDataFeed: 'Live Data Feed',
  dynamicCharacterList: 'Dynamic Character List',
  interactiveDetailView: 'Interactive Detail View',
  offlineSupport: 'Offline Support',
  crossPlatformCompatibility: 'Cross-Platform Compatibility',
  liveDataFeedDescription: '- The app reads a JSON feed directly from the internet, fetching up-to-date information about characters from the Rick and Morty universe.',
  dynamicCharacterListDescription: '- Characters are displayed in a scrollable list format, showing basic info like name and image, making it easy to browse through the multiverse.',
  interactiveDetailViewDescription: '- Tapping on any character opens a dedicated detail screen with expanded information such as species, gender, origin, status, and last known location.',
  offlineSupportDescription: '- Once data is fetched, it\'s stored locally on the device. This means you can still view the characters and their details even without an internet connection.',
  crossPlatformCompatibilityDescription: '- The app is fully compatible and runs smoothly on both Android and iOS platforms via Android Studio, Xcode, or React Native CLI.',
};